---
- block:
    - name: CERTS | Install certs for each Apache vhost or Nginx server block
      command: "certbot --non-interactive --agree-tos --{{ letsencrypt_webserver }} --domains {{ item.value.domain }}"
      with_dict: "{{ letsencrypt_certificates }}"
      when: letsencrypt_autoinstall and item.value.webroot is undefined

    - name: CERTS | Generate certs for each Apache vhost or Nginx server block
      command: "certbot --non-interactive --agree-tos --{{ letsencrypt_webserver }} certonly --domains {{ item.value.domain }}"
      with_dict: "{{ letsencrypt_certificates }}"
      when: letsencrypt_certonly and item.value.webroot is undefined

    - name: CERTS | Create certs when using webroot
      command: "certbot certonly --non-interactive --agree-tos --webroot {{ item.value.webroot }} --domains {{ item.value.domain }}"
      with_dict: "{{ letsencrypt_certificates }}"
      when: item.value.webroot is defined

  when: letsencrypt_webserver == "nginx" or letsencrypt_webserver == "apache"

- block:
    - name: CERTS | Stop webserver
      service:
        name: "{{ letsencrypt_webserver }}"
        state: stopped
      when: letsencrypt_webserver

    - name: CERTS | Create certs when using certonly
      command: "certbot certonly --non-interactive --agree-tos --standalone --domains {{ item.value.domain }}"
      with_dict: "{{ letsencrypt_certificates }}"

    - name: CERTS | Start webserver
      service:
        name: "{{ letsencrypt_webserver }}"
        state: started
      when: letsencrypt_webserver

  when: letsencrypt_standalone or letsencrypt_webserver == ""
