---
- fail: msg="Variable '{{ item }}' is not defined"
     when: item not in hostvars[inventory_hostname]
     with_items:
       - letsencrypt_certs
       - letsencrypt_email

- include: setup.yml
- include: certs.yml
- include: cron.yml
  when: letsencrypt_auto_renew